### ISSUE TITLE
Add possibity to pass #encoding 

### ISSUE THREAD

**Issue by ngiger** [tenderlove/racc#20]
When passing https://github.com/zdavatz/oddb.org/blob/master/data/quanty/parse.y
we always have to manually add a magic comment "# encoding: utf-8". It would be nice to have a possibility that
- either racc passes this line as is
- offers an option to specify the encoding

**Comment by alexdowad** [comment]
One of mmine's original samples, `sample/calc-ja.y`, does have an encoding comment: `# encoding: EUC-JP`.

**Comment by alexdowad** [comment]
...And interestingly enough, mmine's sample doesn't run on an up-to-date Ruby interpreter, due to the same issue!

Looks like passing through the encoding comment is actually a good idea.

**Comment by alexdowad** [comment]
Just pushing a commit to `master` which fixes this...
