### ISSUE TITLE
Weak testing prevents drastic improvement

### ISSUE THREAD

**Issue by headius** [tenderlove/racc#52]
We all know racc could use a lot of cleanup, rework, and optimization. Unfortunately the tests available are a little weak, and folks involved are a bit worried about making drastic changes.

I'm starting this issue after talking to @tenderlove pointed out that we need better tests. I propose that in addition to trying to add unit tests, we could also get racc users like @whitequark and @yorickpeterse to help us incorporate their parsers and parser tests into an integration suite.

Thoughts?

**Comment by alexdowad** [comment]
We have a big integration test suite now, which includes grammars donated from 23 gems which use Racc. If @YorickPeterse and @zenspider have additional grammars which can be used, those are also welcome.
