### ISSUE TITLE
Enable automatic Travis CI builds on each PR

### ISSUE THREAD

**Issue by alexdowad** [tenderlove/racc#56]
To keep Racc ticking smoothly, this is what @tenderlove needs to do! (WARNING: This issue contains a highly professional, impeccably edited screenshot! Do not make fun of it!)

1. Open https://travis-ci.org/tenderlove/racc in your browser. If you already have a (free!) Travis CI account, it will look like this:

![screenshot from 2015-11-03 21 13 09](https://cloud.githubusercontent.com/assets/1067359/10919013/2f1f656c-8271-11e5-98d5-42be0b85b5f7.png)

2. Scroll down and find "tenderlove/racc". Click the gray "X" button, it will turn to a green check.

3. If you've never done this before, Travis CI will redirect to GitHub, where you have to authorize them to monitor your repositories.

4. Make some small grammar or spelling fix (there are plenty to be made), commit to `master`, then push to the repo. This first push will trigger the first Travis CI build.

5. You will find that the `.travis.yml` file is not set up properly to do a working build. I can sort that out and send you a PR.

6. In future, every time someone sends a PR, Travis will automatically pull their code and run a build. I believe the results will appear right in the GitHub PR page! Don't, I said DON'T, press the "merge" button unless the build is green!

7. When you want to work on the code yourself, commit to a topic branch and push the branch to this repo. That should trigger a Travis build of the new branch. If the build is green, go ahead and merge the branch into `master`.

**Comment by tenderlove** [comment]
Should be enabled now. Care to work out the .travis.yml?

**Comment by alexdowad** [comment]
I'll try to do so tomorrow. Thank you!

**Comment by alexdowad** [comment]
Problem with Hoe: it uses a Rake task to install dependencies. But if you don't *already* have the dependencies which are `require`d in the Rakefile, then Rake won't work at all, not even to check which tasks are available! It's a catch-22!

**Comment by alexdowad** [comment]
I wonder if it would hurt us any to use Bundler for dependency management rather than Hoe...?

**Comment by tenderlove** [comment]
What deps do we have? It shouldn't depend on anything outside Ruby stdlib
(since the tests have to run inside trunk Ruby)

**Comment by alexdowad** [comment]
`rake`, `rake-compiler`, and some Hoe stuff.

**Comment by alexdowad** [comment]
Oh, `minitest` is also a dependency. When you say that "the tests have to run inside trunk Ruby", do you mean that building this gem is part of the build process for MRI itself? Could you clarify?

**Comment by tenderlove** [comment]
@alexdowad I have to merge the runtime in to Ruby trunk, so we have to make sure the runtime runs without dependencies.  I don't think it's a problem if we have the Gemfile, we just need to make sure that racc never adds any runtime dependencies.

Also, just so you know some backstory, the compiler part of racc is licensed as GPL, so it *can't* be merged to Ruby trunk, only the runtime part.  So that's fun.

**Comment by alexdowad** [comment]
Understood. Definitely, there will be no runtime dependencies. I would like to add a couple more dev dependencies, though, if it's OK; like SimpleCov to check how much coverage the test suite actually has. From some experimentation, it seems that there may be a significant amount of code without test coverage.

**Comment by tenderlove** [comment]
@alexdowad :+1:

**Comment by alexdowad** [comment]
Test coverage is at 78%.

Turns out that Hoe's `test` task doesn't play nicely with SimpleCov (but I worked around it). Had to send a PR to the SimpleCov guys to make it locate the `.simplecov` config file correctly; hopefully they will accept. For the meantime, I will keep my hacked-up code local-only, but will submit PRs for new tests which increase the coverage.
