### ISSUE TITLE
Allow module namespacing of Parser class

### ISSUE THREAD

**Issue by v0dro** [tenderlove/racc#76]
The following module namespacing for a parser fails:

``` ruby
module Rubex
class Parser
end
end
```

**Comment by zenspider** [comment]
Not sure that this is really necessary. Naming it something better than `Parser` is a start. Then:

```ruby
class RubexParser
end

module Rubex
  Parser = ::RubexParser
end
```

**Comment by alexdowad** [comment]
If a lot of users want this, we will add it later. Closing.
