### ISSUE TITLE
Better error message in case of empty Parser class

### ISSUE THREAD

**Issue by v0dro** [tenderlove/racc#77]
If the Parser class is empty and does not contain any rules, racc fails to generate the parser Ruby file.

This is an unexpected error and should ideally be done away with.

**Comment by alexdowad** [comment]
Every grammar needs a start rule. If there is no start rule, what code do you propose the generated parser should contain?

**Comment by v0dro** [comment]
Ah yes. I'm sorry you have a point.

Then how about having an informative error message incase of an empty Parser class stating that the class cannot be left empty?

**Comment by v0dro** [comment]
It currently shows this: `racc: lib/rubex/parser.racc: parser.racc:3: unexpected token 'end'`

**Comment by alexdowad** [comment]
Sounds good to me. Are you using Racc 1.4.14 or 2.0.0-dev?

**Comment by v0dro** [comment]
1.4.14

**Comment by alexdowad** [comment]
I have pushed a fix for this to `master`.
