### ISSUE TITLE
Build is failing on Ruby 1.9.3 due to incompatibility with latest Rubocop gem

### ISSUE THREAD

**Issue by alexdowad** [tenderlove/racc#79]
...As per the title.

I don't think we can really drop support for Ruby 1.9.3. Or can we?

Should we drop Rubocop instead? Or lock it down to an old version?

Or disable the Rake tasks which use Rubocop when running on 1.9.3?

**Comment by zenspider** [comment]
I'm all for dropping support for 1.9.3, but I'm biased.

That said, there's no reason to run rubocop on multiple versions. Running it on just the latest, or not at all on CI should be fine.

**Comment by alexdowad** [comment]
@zenspider Thanks... now how about other contributors?? Is it OK to kill support for Ruby 1.9.3??

If I get another ACK the axe will drop!

**Comment by alexdowad** [comment]
It seems that nobody else wants to weigh in on this. In the meantime, Ruby 1.9, 2.0, and 2.1 have all been end-of-lifed and are no longer supported. I have just pushed changes which make 2.2 the lowest supported version for this gem. Also pushed some fixes to the test suite which make the build green again.

Please note that the Racc *runtime* is expected to work even on very old versions of Ruby. However, to generate parsers, people should use Ruby 2.2+.
