### ISSUE TITLE
license of parser.rb

### ISSUE THREAD

**Issue by luisapace** [tenderlove/racc#90]

**Comment by luisapace** [comment]
Hi, in ruby 2.2.0 I've found the parser.rb 
<img width="512" alt="image" src="https://user-images.githubusercontent.com/27818611/43014855-e47194ce-8c4d-11e8-8d93-45f9725fc57d.png">

that says at header:
_**# Copyright (c) 1999-2006 Minero Aoki
#
# This program is free software.
# You can distribute/modify this program under the same terms of ruby.**_

but in the body of its code says also:

**_# Note: parser.rb is LGPL, but your parser is not.
# Your own parser is completely yours._**

So, I'm confused:
could you please tell me what is the license of the parser.rb contained in ruby 2.2.0: Ruby or LGPL?  

Thanks a lot for your help.

**Comment by zenspider** [comment]
This is what I see in:

```ruby
# Copyright (c) 1999-2006 Minero Aoki                                           
#                                                                               
# This program is free software.                                                
# You can distribute/modify this program under the same terms of ruby.          
#                                                                               
# As a special exception, when this code is copied by Racc                      
# into a Racc output file, you may use that output file                         
# without restriction.                                                          
```

The generator side of the gem is LGPL. The code that ships with ruby (including parse.rb) is licensed ruby. AFAIK, the note at the bottom that is confusing you is simply mistaken. You'll have to spelunk through SVN (r39050) to find who is responsible for that text.

P.S. (please format your comments nicely)
